language: python

dist: trusty
sudo: required

notifications:
    email: false

python:
    - "3.5"

before_install:
    - pip install tox
    - pip install python-coveralls

script:
    - tox

after_success:
  - coveralls
