"""empty message

Revision ID: 987171517974
Revises: f78f7c6c341f
Create Date: 2018-01-17 12:55:58.625987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '987171517974'
down_revision = 'f78f7c6c341f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reports_metadata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=60), nullable=True),
    sa.Column('live', sa.Boolean(), nullable=True),
    sa.Column('when', sa.DateTime(), nullable=True),
    sa.Column('path', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source')
    )
    op.create_table('reports_checks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('subcategory', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=250), nullable=True),
    sa.Column('plugin_path', sa.String(length=250), nullable=True),
    sa.Column('plugin_id', sa.String(length=50), nullable=True),
    sa.Column('backend', sa.String(length=50), nullable=True),
    sa.Column('long_name', sa.String(length=250), nullable=True),
    sa.Column('bugzilla', sa.String(length=250), nullable=True),
    sa.Column('result_rc', sa.SmallInteger(), nullable=True),
    sa.Column('result_err', sa.Text(), nullable=True),
    sa.Column('result_out', sa.Text(), nullable=True),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['reports_metadata.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=60), nullable=True),
    sa.Column('username', sa.String(length=60), nullable=True),
    sa.Column('first_name', sa.String(length=60), nullable=True),
    sa.Column('last_name', sa.String(length=60), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_first_name'), 'users', ['first_name'], unique=False)
    op.create_index(op.f('ix_users_last_name'), 'users', ['last_name'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('item_type', sa.Integer(), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('employees')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('email', sa.VARCHAR(length=60), nullable=True),
    sa.Column('username', sa.VARCHAR(length=60), nullable=True),
    sa.Column('first_name', sa.VARCHAR(length=60), nullable=True),
    sa.Column('last_name', sa.VARCHAR(length=60), nullable=True),
    sa.Column('password_hash', sa.VARCHAR(length=128), nullable=True),
    sa.Column('department_id', sa.INTEGER(), nullable=True),
    sa.Column('role_id', sa.INTEGER(), nullable=True),
    sa.Column('is_admin', sa.BOOLEAN(), nullable=True),
    sa.CheckConstraint(u'is_admin IN (0, 1)'),
    sa.ForeignKeyConstraint(['department_id'], [u'departments.id'], ),
    sa.ForeignKeyConstraint(['role_id'], [u'roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('history')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_last_name'), table_name='users')
    op.drop_index(op.f('ix_users_first_name'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('reports_checks')
    op.drop_table('reports_metadata')
    # ### end Alembic commands ###
